import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/shared/Navbar";
import Footer from "@/components/shared/Footer";
import AuthProvider from "./authProvider/AuthProvider";
import { ToastContainer } from "react-toastify";
import QueryProvider from "@/components/lib/QueryProvider";
import '@smastrom/react-rating/style.css'


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Admission Aid",
  description: "Generated by create next app",
    icons: {
    icon: '/assets/logo-AddAid.jpg', 
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={` ${geistSans.variable} ${geistMono.variable} antialiased bg-stone-300 text-gray-800 dark:bg-black dark:text-white`}
      >
        <AuthProvider>
          <QueryProvider>
          <Navbar />
          <ToastContainer/>
          {children}
          <Footer />
          </QueryProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
